language: node_js
node_js:
  - "10"
dist: trusty
sudo: required

branches:
  only:
  - release

before_install:
  - rm -f npm-shrinkwrap.json


before_script:
  - npm install -g react-scripts

cache:
  directories:
    - "node_modules"

install: npm install

script:
- npm run deploy:prod
- mv dist/index.html dist/404.html

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: release
  target-branch: master
